/**
 * Sharp's 198 Methods of Nonviolent Action, structured by class.
 * Source: Gene Sharp, "The Politics of Nonviolent Action" (1973),
 *         Albert Einstein Institution.
 */

export const METHODS = [
  // ─── CLASS 1: NONVIOLENT PROTEST AND PERSUASION (1–54) ───────────────────
  { number: 1, name: 'Public speeches', class: 'protest_persuasion', category: 'Formal Statements' },
  { number: 2, name: 'Letters of opposition or support', class: 'protest_persuasion', category: 'Formal Statements' },
  { number: 3, name: 'Declarations by organizations and institutions', class: 'protest_persuasion', category: 'Formal Statements' },
  { number: 4, name: 'Signed public statements', class: 'protest_persuasion', category: 'Formal Statements' },
  { number: 5, name: 'Declarations of indictment and intention', class: 'protest_persuasion', category: 'Formal Statements' },
  { number: 6, name: 'Group or mass petitions', class: 'protest_persuasion', category: 'Formal Statements' },
  { number: 7, name: 'Slogans, caricatures, and symbols', class: 'protest_persuasion', category: 'Communications with a Wider Audience' },
  { number: 8, name: 'Banners, posters, and displayed communications', class: 'protest_persuasion', category: 'Communications with a Wider Audience' },
  { number: 9, name: 'Leaflets, pamphlets, and books', class: 'protest_persuasion', category: 'Communications with a Wider Audience' },
  { number: 10, name: 'Newspapers and journals', class: 'protest_persuasion', category: 'Communications with a Wider Audience' },
  { number: 11, name: 'Records, radio, and television', class: 'protest_persuasion', category: 'Communications with a Wider Audience' },
  { number: 12, name: 'Skywriting and earthwriting', class: 'protest_persuasion', category: 'Communications with a Wider Audience' },
  { number: 13, name: 'Deputations', class: 'protest_persuasion', category: 'Group Representations' },
  { number: 14, name: 'Mock awards', class: 'protest_persuasion', category: 'Group Representations' },
  { number: 15, name: 'Group lobbying', class: 'protest_persuasion', category: 'Group Representations' },
  { number: 16, name: 'Picketing', class: 'protest_persuasion', category: 'Group Representations' },
  { number: 17, name: 'Mock elections', class: 'protest_persuasion', category: 'Group Representations' },
  { number: 18, name: 'Display of flags and symbolic colors', class: 'protest_persuasion', category: 'Symbolic Public Acts' },
  { number: 19, name: 'Wearing of symbols', class: 'protest_persuasion', category: 'Symbolic Public Acts' },
  { number: 20, name: 'Prayer and worship', class: 'protest_persuasion', category: 'Symbolic Public Acts' },
  { number: 21, name: 'Delivering symbolic objects', class: 'protest_persuasion', category: 'Symbolic Public Acts' },
  { number: 22, name: 'Protest disrobings', class: 'protest_persuasion', category: 'Symbolic Public Acts' },
  { number: 23, name: 'Destruction of own property', class: 'protest_persuasion', category: 'Symbolic Public Acts' },
  { number: 24, name: 'Symbolic lights', class: 'protest_persuasion', category: 'Symbolic Public Acts' },
  { number: 25, name: 'Displays of portraits', class: 'protest_persuasion', category: 'Symbolic Public Acts' },
  { number: 26, name: 'Paint as protest', class: 'protest_persuasion', category: 'Symbolic Public Acts' },
  { number: 27, name: 'New signs and names', class: 'protest_persuasion', category: 'Symbolic Public Acts' },
  { number: 28, name: 'Symbolic sounds', class: 'protest_persuasion', category: 'Symbolic Public Acts' },
  { number: 29, name: 'Symbolic reclamations', class: 'protest_persuasion', category: 'Symbolic Public Acts' },
  { number: 30, name: 'Rude gestures', class: 'protest_persuasion', category: 'Symbolic Public Acts' },
  { number: 31, name: '"Haunting" officials', class: 'protest_persuasion', category: 'Pressures on Individuals' },
  { number: 32, name: 'Taunting officials', class: 'protest_persuasion', category: 'Pressures on Individuals' },
  { number: 33, name: 'Fraternization', class: 'protest_persuasion', category: 'Pressures on Individuals' },
  { number: 34, name: 'Vigils', class: 'protest_persuasion', category: 'Pressures on Individuals' },
  { number: 35, name: 'Humorous skits and pranks', class: 'protest_persuasion', category: 'Drama and Music' },
  { number: 36, name: 'Performances of plays and music', class: 'protest_persuasion', category: 'Drama and Music' },
  { number: 37, name: 'Singing', class: 'protest_persuasion', category: 'Drama and Music' },
  { number: 38, name: 'Marches', class: 'protest_persuasion', category: 'Processions' },
  { number: 39, name: 'Parades', class: 'protest_persuasion', category: 'Processions' },
  { number: 40, name: 'Religious processions', class: 'protest_persuasion', category: 'Processions' },
  { number: 41, name: 'Pilgrimages', class: 'protest_persuasion', category: 'Processions' },
  { number: 42, name: 'Motorcades', class: 'protest_persuasion', category: 'Processions' },
  { number: 43, name: 'Political mourning', class: 'protest_persuasion', category: 'Honoring the Dead' },
  { number: 44, name: 'Mock funerals', class: 'protest_persuasion', category: 'Honoring the Dead' },
  { number: 45, name: 'Demonstrative funerals', class: 'protest_persuasion', category: 'Honoring the Dead' },
  { number: 46, name: 'Homage at burial places', class: 'protest_persuasion', category: 'Honoring the Dead' },
  { number: 47, name: 'Assemblies of protest or support', class: 'protest_persuasion', category: 'Public Assemblies' },
  { number: 48, name: 'Protest meetings', class: 'protest_persuasion', category: 'Public Assemblies' },
  { number: 49, name: 'Camouflaged meetings of protest', class: 'protest_persuasion', category: 'Public Assemblies' },
  { number: 50, name: 'Teach-ins', class: 'protest_persuasion', category: 'Public Assemblies' },
  { number: 51, name: 'Walk-outs', class: 'protest_persuasion', category: 'Withdrawal and Renunciation' },
  { number: 52, name: 'Silence', class: 'protest_persuasion', category: 'Withdrawal and Renunciation' },
  { number: 53, name: 'Renouncing honors', class: 'protest_persuasion', category: 'Withdrawal and Renunciation' },
  { number: 54, name: 'Turning one\'s back', class: 'protest_persuasion', category: 'Withdrawal and Renunciation' },

  // ─── CLASS 2: SOCIAL NONCOOPERATION (55–70) ──────────────────────────────
  { number: 55, name: 'Social boycott', class: 'noncooperation', category: 'Social Noncooperation' },
  { number: 56, name: 'Selective social boycott', class: 'noncooperation', category: 'Social Noncooperation' },
  { number: 57, name: 'Lysistratic nonaction', class: 'noncooperation', category: 'Social Noncooperation' },
  { number: 58, name: 'Excommunication', class: 'noncooperation', category: 'Social Noncooperation' },
  { number: 59, name: 'Interdict', class: 'noncooperation', category: 'Social Noncooperation' },
  { number: 60, name: 'Suspension of social and sports activities', class: 'noncooperation', category: 'Social Noncooperation' },
  { number: 61, name: 'Boycott of social affairs', class: 'noncooperation', category: 'Social Noncooperation' },
  { number: 62, name: 'Student strike', class: 'noncooperation', category: 'Social Noncooperation' },
  { number: 63, name: 'Social disobedience', class: 'noncooperation', category: 'Social Noncooperation' },
  { number: 64, name: 'Withdrawal from social institutions', class: 'noncooperation', category: 'Social Noncooperation' },
  { number: 65, name: 'Stay-at-home', class: 'noncooperation', category: 'Social Noncooperation' },
  { number: 66, name: 'Total personal noncooperation', class: 'noncooperation', category: 'Social Noncooperation' },
  { number: 67, name: 'Flight of workers', class: 'noncooperation', category: 'Social Noncooperation' },
  { number: 68, name: 'Sanctuary', class: 'noncooperation', category: 'Social Noncooperation' },
  { number: 69, name: 'Collective disappearance', class: 'noncooperation', category: 'Social Noncooperation' },
  { number: 70, name: 'Protest emigration (hijrat)', class: 'noncooperation', category: 'Social Noncooperation' },

  // Economic Noncooperation: Boycotts (71–96)
  { number: 71, name: 'Consumers\' boycott', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 72, name: 'Nonconsumption of boycotted goods', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 73, name: 'Policy of austerity', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 74, name: 'Rent withholding', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 75, name: 'Refusal to rent', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 76, name: 'National consumers\' boycott', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 77, name: 'International consumers\' boycott', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 78, name: 'Workers\' boycott', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 79, name: 'Producers\' boycott', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 80, name: 'Suppliers\' and handlers\' boycott', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 81, name: 'Traders\' boycott', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 82, name: 'Refusal to let or sell property', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 83, name: 'Lockout', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 84, name: 'Refusal of industrial assistance', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 85, name: 'Merchants\' "general strike"', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 86, name: 'Withdrawal of bank deposits', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 87, name: 'Refusal to pay fees, dues, and assessments', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 88, name: 'Refusal to pay debts or interest', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 89, name: 'Severance of funds and credit', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 90, name: 'Revenue refusal', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 91, name: 'Refusal of a government\'s money', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 92, name: 'Domestic embargo', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 93, name: 'Blacklisting of traders', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 94, name: 'International sellers\' embargo', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 95, name: 'International buyers\' embargo', class: 'noncooperation', category: 'Economic Boycotts' },
  { number: 96, name: 'International trade embargo', class: 'noncooperation', category: 'Economic Boycotts' },

  // Economic Noncooperation: Strikes (97–127)
  { number: 97, name: 'Protest strike', class: 'noncooperation', category: 'Strikes' },
  { number: 98, name: 'Quickie walkout (lightning strike)', class: 'noncooperation', category: 'Strikes' },
  { number: 99, name: 'Peasant strike', class: 'noncooperation', category: 'Strikes' },
  { number: 100, name: 'Farm workers\' strike', class: 'noncooperation', category: 'Strikes' },
  { number: 101, name: 'Refusal of impressed labor', class: 'noncooperation', category: 'Strikes' },
  { number: 102, name: 'Prisoners\' strike', class: 'noncooperation', category: 'Strikes' },
  { number: 103, name: 'Craft strike', class: 'noncooperation', category: 'Strikes' },
  { number: 104, name: 'Professional strike', class: 'noncooperation', category: 'Strikes' },
  { number: 105, name: 'Establishment strike', class: 'noncooperation', category: 'Strikes' },
  { number: 106, name: 'Industry strike', class: 'noncooperation', category: 'Strikes' },
  { number: 107, name: 'Sympathetic strike', class: 'noncooperation', category: 'Strikes' },
  { number: 108, name: 'Detailed strike', class: 'noncooperation', category: 'Strikes' },
  { number: 109, name: 'Bumper strike', class: 'noncooperation', category: 'Strikes' },
  { number: 110, name: 'Slowdown strike', class: 'noncooperation', category: 'Strikes' },
  { number: 111, name: 'Working-to-rule strike', class: 'noncooperation', category: 'Strikes' },
  { number: 112, name: 'Reporting "sick" (sick-in)', class: 'noncooperation', category: 'Strikes' },
  { number: 113, name: 'Strike by resignation', class: 'noncooperation', category: 'Strikes' },
  { number: 114, name: 'Limited strike', class: 'noncooperation', category: 'Strikes' },
  { number: 115, name: 'Selective strike', class: 'noncooperation', category: 'Strikes' },
  { number: 116, name: 'Generalized strike', class: 'noncooperation', category: 'Strikes' },
  { number: 117, name: 'General strike', class: 'noncooperation', category: 'Strikes' },
  { number: 118, name: 'Hartal', class: 'noncooperation', category: 'Strikes' },
  { number: 119, name: 'Economic shutdown', class: 'noncooperation', category: 'Strikes' },

  // Political Noncooperation (120–148)
  { number: 120, name: 'Withholding or withdrawal of allegiance', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 121, name: 'Refusal of public support', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 122, name: 'Literature and speeches advocating resistance', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 123, name: 'Boycott of legislative bodies', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 124, name: 'Boycott of elections', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 125, name: 'Boycott of government employment and positions', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 126, name: 'Boycott of government departments, agencies, and bodies', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 127, name: 'Withdrawal from government educational institutions', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 128, name: 'Boycott of government-supported organizations', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 129, name: 'Refusal of assistance to enforcement agents', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 130, name: 'Removal of own signs and placemarks', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 131, name: 'Refusal to accept appointed officials', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 132, name: 'Refusal to dissolve existing institutions', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 133, name: 'Popular nonobedience', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 134, name: 'Nonobedience in absence of direct supervision', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 135, name: 'Popular nonobedience', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 136, name: 'Disguised disobedience', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 137, name: 'Refusal of an assemblage or meeting to disperse', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 138, name: 'Sit-down', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 139, name: 'Noncooperation with conscription and deportation', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 140, name: 'Hiding, escape, and false identities', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 141, name: 'Civil disobedience of "neutral" laws', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 142, name: 'Selective refusal of assistance by government aides', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 143, name: 'Blocking of lines of command and information', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 144, name: 'Stalling and obstruction', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 145, name: 'General administrative noncooperation', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 146, name: 'Judicial noncooperation', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 147, name: 'Deliberate inefficiency and selective noncooperation by enforcement agents', class: 'noncooperation', category: 'Political Noncooperation' },
  { number: 148, name: 'Mutiny', class: 'noncooperation', category: 'Political Noncooperation' },

  // ─── CLASS 3: NONVIOLENT INTERVENTION (149–198) ───────────────────────────
  { number: 149, name: 'Self-exposure to the elements', class: 'intervention', category: 'Psychological Intervention' },
  { number: 150, name: 'The fast', class: 'intervention', category: 'Psychological Intervention' },
  { number: 151, name: 'Reverse trial', class: 'intervention', category: 'Psychological Intervention' },
  { number: 152, name: 'Nonviolent harassment', class: 'intervention', category: 'Psychological Intervention' },
  { number: 153, name: 'Sit-in', class: 'intervention', category: 'Physical Intervention' },
  { number: 154, name: 'Stand-in', class: 'intervention', category: 'Physical Intervention' },
  { number: 155, name: 'Ride-in', class: 'intervention', category: 'Physical Intervention' },
  { number: 156, name: 'Wade-in', class: 'intervention', category: 'Physical Intervention' },
  { number: 157, name: 'Mill-in', class: 'intervention', category: 'Physical Intervention' },
  { number: 158, name: 'Pray-in', class: 'intervention', category: 'Physical Intervention' },
  { number: 159, name: 'Nonviolent raids', class: 'intervention', category: 'Physical Intervention' },
  { number: 160, name: 'Nonviolent air raids', class: 'intervention', category: 'Physical Intervention' },
  { number: 161, name: 'Nonviolent invasion', class: 'intervention', category: 'Physical Intervention' },
  { number: 162, name: 'Nonviolent interjection', class: 'intervention', category: 'Physical Intervention' },
  { number: 163, name: 'Nonviolent obstruction', class: 'intervention', category: 'Physical Intervention' },
  { number: 164, name: 'Nonviolent occupation', class: 'intervention', category: 'Physical Intervention' },
  { number: 165, name: 'Establishing new social patterns', class: 'intervention', category: 'Social Intervention' },
  { number: 166, name: 'Overloading of facilities', class: 'intervention', category: 'Social Intervention' },
  { number: 167, name: 'Stall-in', class: 'intervention', category: 'Social Intervention' },
  { number: 168, name: 'Speak-in', class: 'intervention', category: 'Social Intervention' },
  { number: 169, name: 'Guerrilla theater', class: 'intervention', category: 'Social Intervention' },
  { number: 170, name: 'Alternative social institutions', class: 'intervention', category: 'Social Intervention' },
  { number: 171, name: 'Alternative communication system', class: 'intervention', category: 'Social Intervention' },
  { number: 172, name: 'Reverse strike', class: 'intervention', category: 'Economic Intervention' },
  { number: 173, name: 'Stay-in strike', class: 'intervention', category: 'Economic Intervention' },
  { number: 174, name: 'Nonviolent land seizure', class: 'intervention', category: 'Economic Intervention' },
  { number: 175, name: 'Defiance of blockades', class: 'intervention', category: 'Economic Intervention' },
  { number: 176, name: 'Politically motivated counterfeiting', class: 'intervention', category: 'Economic Intervention' },
  { number: 177, name: 'Preclusive purchasing', class: 'intervention', category: 'Economic Intervention' },
  { number: 178, name: 'Seizure of assets', class: 'intervention', category: 'Economic Intervention' },
  { number: 179, name: 'Dumping', class: 'intervention', category: 'Economic Intervention' },
  { number: 180, name: 'Selective patronage', class: 'intervention', category: 'Economic Intervention' },
  { number: 181, name: 'Alternative markets', class: 'intervention', category: 'Economic Intervention' },
  { number: 182, name: 'Alternative transportation systems', class: 'intervention', category: 'Economic Intervention' },
  { number: 183, name: 'Alternative economic institutions', class: 'intervention', category: 'Economic Intervention' },
  { number: 184, name: 'Overloading of administrative systems', class: 'intervention', category: 'Political Intervention' },
  { number: 185, name: 'Disclosing identities of secret agents', class: 'intervention', category: 'Political Intervention' },
  { number: 186, name: 'Seeking imprisonment', class: 'intervention', category: 'Political Intervention' },
  { number: 187, name: 'Civil disobedience of "neutral" laws', class: 'intervention', category: 'Political Intervention' },
  { number: 188, name: 'Work-on without collaboration', class: 'intervention', category: 'Political Intervention' },
  { number: 189, name: 'Dual sovereignty and parallel government', class: 'intervention', category: 'Political Intervention' },
  { number: 190, name: 'Self-immolation', class: 'intervention', category: 'Political Intervention' },
  { number: 191, name: 'Quasi-legal evasions and delays', class: 'intervention', category: 'Political Intervention' },
  { number: 192, name: 'Nonviolent obstruction', class: 'intervention', category: 'Political Intervention' },
  { number: 193, name: 'Establishment of new government organs', class: 'intervention', category: 'Political Intervention' },
  { number: 194, name: 'Delay and cancellation of diplomatic events', class: 'intervention', category: 'Political Intervention' },
  { number: 195, name: 'Withholding of diplomatic recognition', class: 'intervention', category: 'Political Intervention' },
  { number: 196, name: 'Severance of diplomatic relations', class: 'intervention', category: 'Political Intervention' },
  { number: 197, name: 'Withdrawal from international organizations', class: 'intervention', category: 'Political Intervention' },
  { number: 198, name: 'Expulsion from international organizations', class: 'intervention', category: 'Political Intervention' },
];

export function getMethods(classFilter) {
  const methods = classFilter ? METHODS.filter(m => m.class === classFilter) : METHODS;
  return methods;
}
